# Generated by Django 4.2.5 on 2023-09-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100)),
                ('type_ru', models.CharField(max_length=100, null=True)),
                ('type_en', models.CharField(max_length=100, null=True)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('genre', models.CharField(max_length=50)),
                ('genre_ru', models.CharField(max_length=50, null=True)),
                ('genre_en', models.CharField(max_length=50, null=True)),
                ('director_1', models.CharField(max_length=50)),
                ('director_1_ru', models.CharField(max_length=50, null=True)),
                ('director_1_en', models.CharField(max_length=50, null=True)),
                ('director_2', models.CharField(blank=True, max_length=50)),
                (
                    'director_2_ru',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'director_2_en',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ('star_1', models.CharField(blank=True, max_length=50)),
                (
                    'star_1_ru',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'star_1_en',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ('star_2', models.CharField(blank=True, max_length=50)),
                (
                    'star_2_ru',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'star_2_en',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ('star_3', models.CharField(blank=True, max_length=50)),
                (
                    'star_3_ru',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    'star_3_en',
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ('kp', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdb', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField(max_length=185)),
                (
                    'description_ru',
                    models.TextField(max_length=185, null=True),
                ),
                (
                    'description_en',
                    models.TextField(max_length=185, null=True),
                ),
                (
                    'poster',
                    models.ImageField(
                        blank=True,
                        default='posters/noposter.png',
                        upload_to='posters/',
                    ),
                ),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'movie',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='viewers',
                        to='movies.movie',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='films',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(
                fields=('title', 'year', 'director_1'), name='unique_movie'
            ),
        ),
        migrations.AddConstraint(
            model_name='usermovie',
            constraint=models.UniqueConstraint(
                fields=('user', 'movie'), name='unique_user_movie'
            ),
        ),
    ]
